import type { PlazaEntryConfig } from '@/types/plazaConfig'

/** 本地默认广场入口（远端按 key 覆盖；sort_order 控制顺序） */
export const PLAZA_ENTRIES_DEFAULT: PlazaEntryConfig[] = [
  {
    key: 'favorites',
    title: '收藏',
    subtitle: '查看已保存的菜谱',
    route: '/pages/favorites/index',
    enabled: true,
    sort_order: 10,
    coming_soon: false,
  },
  {
    key: 'histories',
    title: '历史',
    subtitle: '最近生成记录',
    route: '/pages/histories/index',
    enabled: true,
    sort_order: 20,
    coming_soon: false,
  },
  {
    key: 'me',
    title: '我的',
    subtitle: '登录与账号',
    route: '/pages/me/index',
    enabled: true,
    sort_order: 30,
    coming_soon: false,
  },
  {
    key: 'table-design',
    title: '一桌好菜',
    subtitle: '满汉全席',
    route: '/pages/table-menu/index',
    enabled: true,
    sort_order: 40,
    coming_soon: false,
  },
  {
    key: 'fortune',
    title: '玄学厨房',
    subtitle: '运势·心情·数字·缘分',
    route: '/pages/fortune-cooking/index',
    enabled: true,
    sort_order: 50,
    coming_soon: false,
  },
  {
    key: 'sauce',
    title: '酱料大师',
    subtitle: '推荐与配方',
    route: '/pages/sauce-design/index',
    enabled: true,
    sort_order: 60,
    coming_soon: false,
  },
  {
    key: 'gallery',
    title: '图鉴',
    subtitle: '封神图鉴',
    route: '/pages/gallery/index',
    enabled: true,
    sort_order: 70,
    coming_soon: false,
  },
]
