<?php

/**
 * MVP 结构化菜品池：用于规则打分与多样性约束；模型须在提示内优先从此池择菜。
 *
 * @return list<array{
 *   name: string,
 *   flavor_tags: list<string>,
 *   cuisine_type: string,
 *   cooking_complexity: 'quick'|'medium'|'heavy',
 *   suitable_scene: 'solo'|'couple'|'family',
 *   health_tags: list<string>,
 *   temperature_tags: list<string>,
 *   ingredients: list<string>
 * }>
 */
return [
    ['name' => '番茄鸡蛋面', 'flavor_tags' => ['家常', '酸甜', '清淡'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['均衡'], 'temperature_tags' => ['warm'], 'ingredients' => ['番茄', '鸡蛋', '面条', '葱']],
    ['name' => '清蒸鲈鱼', 'flavor_tags' => ['清淡', '鲜美'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['鲈鱼', '姜', '葱', '蒸鱼豉油']],
    ['name' => '麻婆豆腐', 'flavor_tags' => ['麻辣', '下饭'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'quick', 'suitable_scene' => 'couple', 'health_tags' => ['植物蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['豆腐', '牛肉末', '豆瓣酱', '花椒']],
    ['name' => '冬瓜排骨汤', 'flavor_tags' => ['清淡', '暖胃'], 'cuisine_type' => 'home', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['冬瓜', '排骨', '姜', '葱']],
    ['name' => '白灼菜心', 'flavor_tags' => ['清淡', '爽脆'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高纤维', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['菜心', '蒜', '生抽']],
    ['name' => '红烧肉', 'flavor_tags' => ['酱香', '浓郁'], 'cuisine_type' => 'shanghai', 'cooking_complexity' => 'heavy', 'suitable_scene' => 'family', 'health_tags' => [], 'temperature_tags' => ['hot'], 'ingredients' => ['五花肉', '冰糖', '生抽', '姜']],
    ['name' => '香菇青菜', 'flavor_tags' => ['清淡', '家常'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高纤维'], 'temperature_tags' => ['warm'], 'ingredients' => ['香菇', '青菜', '蒜']],
    ['name' => '黑椒牛柳', 'flavor_tags' => ['黑椒', '咸鲜'], 'cuisine_type' => 'fusion', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['牛里脊', '青椒', '洋葱', '黑胡椒']],
    ['name' => '凉拌黄瓜', 'flavor_tags' => ['清爽', '酸辣'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['低脂'], 'temperature_tags' => ['cold'], 'ingredients' => ['黄瓜', '蒜', '醋', '辣椒油']],
    ['name' => '咖喱鸡饭', 'flavor_tags' => ['咖喱', '香浓'], 'cuisine_type' => 'fusion', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['鸡腿', '土豆', '胡萝卜', '咖喱块']],
    ['name' => '虾仁蒸蛋', 'flavor_tags' => ['嫩滑', '清淡'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['鸡蛋', '虾仁', '温水', '盐']],
    ['name' => '青椒土豆丝', 'flavor_tags' => ['家常', '微酸'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['土豆', '青椒', '醋', '蒜']],
    ['name' => '酸菜鱼', 'flavor_tags' => ['酸辣', '开胃'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'heavy', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['黑鱼', '酸菜', '泡椒', '豆皮']],
    ['name' => '糖醋里脊', 'flavor_tags' => ['酸甜', '外酥'], 'cuisine_type' => 'shandong', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => [], 'temperature_tags' => ['hot'], 'ingredients' => ['猪里脊', '番茄沙司', '糖', '淀粉']],
    ['name' => '蚝油生菜', 'flavor_tags' => ['清淡', '鲜甜'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['低脂', '高纤维'], 'temperature_tags' => ['warm'], 'ingredients' => ['生菜', '蚝油', '蒜']],
    ['name' => '宫保鸡丁', 'flavor_tags' => ['微辣', '酸甜'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['鸡胸肉', '花生米', '干辣椒', '葱']],
    ['name' => '蒜泥西兰花', 'flavor_tags' => ['清淡', '蒜香'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高纤维', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['西兰花', '蒜', '盐']],
    ['name' => '皮蛋瘦肉粥', 'flavor_tags' => ['暖胃', '咸鲜'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'medium', 'suitable_scene' => 'solo', 'health_tags' => ['易消化'], 'temperature_tags' => ['warm'], 'ingredients' => ['大米', '瘦肉', '皮蛋', '姜']],
    ['name' => '韭菜盒子', 'flavor_tags' => ['香脆', '家常'], 'cuisine_type' => 'northern', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => [], 'temperature_tags' => ['hot'], 'ingredients' => ['韭菜', '鸡蛋', '面粉']],
    ['name' => '口水鸡', 'flavor_tags' => ['麻辣', '凉菜'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['cold'], 'ingredients' => ['鸡腿', '花生', '辣椒油', '芝麻']],
    ['name' => '扬州炒饭', 'flavor_tags' => ['家常', '粒粒分明'], 'cuisine_type' => 'jiangsu', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['主食'], 'temperature_tags' => ['hot'], 'ingredients' => ['米饭', '鸡蛋', '火腿', '豌豆']],
    ['name' => '砂锅粥', 'flavor_tags' => ['暖胃', '鲜美'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['易消化'], 'temperature_tags' => ['warm'], 'ingredients' => ['大米', '鲜虾', '冬菜', '姜']],
    ['name' => '京酱肉丝', 'flavor_tags' => ['酱香', '甜咸'], 'cuisine_type' => 'beijing', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['warm'], 'ingredients' => ['猪里脊', '甜姜酱', '豆腐皮', '葱']],
    ['name' => '凉拌木耳', 'flavor_tags' => ['清爽', '微辣'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高纤维', '低脂'], 'temperature_tags' => ['cold'], 'ingredients' => ['木耳', '香菜', '醋', '辣椒油']],
    ['name' => '小炒黄牛肉', 'flavor_tags' => ['香辣', '下饭'], 'cuisine_type' => 'hunan', 'cooking_complexity' => 'quick', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['黄牛肉', '小米辣', '姜', '蒜']],
    ['name' => '西红柿炖牛腩', 'flavor_tags' => ['酸甜', '浓郁'], 'cuisine_type' => 'home', 'cooking_complexity' => 'heavy', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白', '补铁'], 'temperature_tags' => ['warm'], 'ingredients' => ['牛腩', '番茄', '土豆', '姜']],
    ['name' => '葱油拌面', 'flavor_tags' => ['葱香', '家常'], 'cuisine_type' => 'shanghai', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['主食'], 'temperature_tags' => ['warm'], 'ingredients' => ['面条', '小葱', '酱油', '油']],
    ['name' => '蒸水蛋', 'flavor_tags' => ['嫩滑', '清淡'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['鸡蛋', '温水', '盐']],
    ['name' => '红烧茄子', 'flavor_tags' => ['酱香', '软糯'], 'cuisine_type' => 'home', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => ['高纤维'], 'temperature_tags' => ['hot'], 'ingredients' => ['茄子', '蒜', '生抽', '糖']],
    ['name' => '玉米排骨汤', 'flavor_tags' => ['清甜', '暖胃'], 'cuisine_type' => 'home', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['玉米', '排骨', '胡萝卜', '姜']],
    ['name' => '蚂蚁上树', 'flavor_tags' => ['微辣', '下饭'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'quick', 'suitable_scene' => 'couple', 'health_tags' => [], 'temperature_tags' => ['hot'], 'ingredients' => ['粉丝', '肉末', '豆瓣酱', '葱']],
    ['name' => '紫菜蛋花汤', 'flavor_tags' => ['清淡', '暖胃'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'family', 'health_tags' => ['低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['紫菜', '鸡蛋', '香油', '虾皮']],
    ['name' => '回锅肉', 'flavor_tags' => ['香辣', '下饭'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => [], 'temperature_tags' => ['hot'], 'ingredients' => ['五花肉', '青椒', '蒜苗', '郫县豆瓣']],
    ['name' => '清炒虾仁', 'flavor_tags' => ['清淡', '鲜甜'], 'cuisine_type' => 'jiangsu', 'cooking_complexity' => 'quick', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['虾仁', '黄瓜', '蛋清', '淀粉']],
    ['name' => '口水娃娃菜', 'flavor_tags' => ['微辣', '清爽'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['低脂'], 'temperature_tags' => ['cold'], 'ingredients' => ['娃娃菜', '醋', '辣椒油', '蒜']],
    ['name' => '意大利番茄肉酱面', 'flavor_tags' => ['番茄', '奶香'], 'cuisine_type' => 'western', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['意面', '牛肉末', '番茄', '洋葱']],
    ['name' => '韭菜炒蛋', 'flavor_tags' => ['家常', '鲜香'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['韭菜', '鸡蛋', '盐']],
    ['name' => '照烧鸡腿饭', 'flavor_tags' => ['甜咸', '多汁'], 'cuisine_type' => 'japanese', 'cooking_complexity' => 'medium', 'suitable_scene' => 'solo', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['鸡腿', '照烧汁', '西兰花', '米饭']],
    ['name' => '蒜蓉粉丝蒸虾', 'flavor_tags' => ['蒜香', '鲜美'], 'cuisine_type' => 'cantonese', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['hot'], 'ingredients' => ['大虾', '粉丝', '蒜蓉', '生抽']],
    ['name' => '牛肉炖土豆', 'flavor_tags' => ['浓郁', '暖胃'], 'cuisine_type' => 'home', 'cooking_complexity' => 'heavy', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['warm'], 'ingredients' => ['牛腩', '土豆', '胡萝卜', '姜']],
    ['name' => '干煸四季豆', 'flavor_tags' => ['干香', '微辣'], 'cuisine_type' => 'sichuan', 'cooking_complexity' => 'medium', 'suitable_scene' => 'couple', 'health_tags' => ['高纤维'], 'temperature_tags' => ['hot'], 'ingredients' => ['四季豆', '肉末', '干辣椒', '花椒']],
    ['name' => '三杯鸡', 'flavor_tags' => ['酱香', '微甜'], 'cuisine_type' => 'taiwan', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白'], 'temperature_tags' => ['hot'], 'ingredients' => ['鸡腿', '香油', '米酒', '酱油']],
    ['name' => '鲫鱼豆腐汤', 'flavor_tags' => ['清淡', '鲜美'], 'cuisine_type' => 'home', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['高蛋白', '低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['鲫鱼', '豆腐', '姜', '葱']],
    ['name' => '酸辣土豆丝', 'flavor_tags' => ['酸辣', '爽脆'], 'cuisine_type' => 'home', 'cooking_complexity' => 'quick', 'suitable_scene' => 'solo', 'health_tags' => ['低脂'], 'temperature_tags' => ['warm'], 'ingredients' => ['土豆', '醋', '干辣椒', '青椒']],
    ['name' => '法式洋葱汤', 'flavor_tags' => ['浓郁', '甜香'], 'cuisine_type' => 'western', 'cooking_complexity' => 'heavy', 'suitable_scene' => 'couple', 'health_tags' => [], 'temperature_tags' => ['warm'], 'ingredients' => ['洋葱', '牛肉高汤', '芝士', '面包']],
    ['name' => '泰式冬阴功汤', 'flavor_tags' => ['酸辣', '开胃'], 'cuisine_type' => 'thai', 'cooking_complexity' => 'medium', 'suitable_scene' => 'family', 'health_tags' => ['低脂'], 'temperature_tags' => ['hot'], 'ingredients' => ['大虾', '香茅', '柠檬叶', '椰浆']],
];
