<?php

/**
 * 公历日期对应的节气（按年维护，便于推荐「今天感」；非精确天文，每年可校对）。
 * 每条为当日进入的节气（节气日当日及之后至下一节气前归属本节气）。
 *
 * @return array<string, list<array{month: int, day: int, key: string, name: string}>>
 */
return [
    '2024' => [
        ['month' => 1, 'day' => 6, 'key' => 'xiaohan', 'name' => '小寒'],
        ['month' => 1, 'day' => 20, 'key' => 'dahan', 'name' => '大寒'],
        ['month' => 2, 'day' => 4, 'key' => 'lichun', 'name' => '立春'],
        ['month' => 2, 'day' => 19, 'key' => 'yushui', 'name' => '雨水'],
        ['month' => 3, 'day' => 5, 'key' => 'jingzhe', 'name' => '惊蛰'],
        ['month' => 3, 'day' => 20, 'key' => 'chunfen', 'name' => '春分'],
        ['month' => 4, 'day' => 4, 'key' => 'qingming', 'name' => '清明'],
        ['month' => 4, 'day' => 19, 'key' => 'guyu', 'name' => '谷雨'],
        ['month' => 5, 'day' => 5, 'key' => 'lixia', 'name' => '立夏'],
        ['month' => 5, 'day' => 20, 'key' => 'xiaoman', 'name' => '小满'],
        ['month' => 6, 'day' => 5, 'key' => 'mangzhong', 'name' => '芒种'],
        ['month' => 6, 'day' => 21, 'key' => 'xiazhi', 'name' => '夏至'],
        ['month' => 7, 'day' => 6, 'key' => 'xiaoshu', 'name' => '小暑'],
        ['month' => 7, 'day' => 22, 'key' => 'dashu', 'name' => '大暑'],
        ['month' => 8, 'day' => 7, 'key' => 'liqiu', 'name' => '立秋'],
        ['month' => 8, 'day' => 22, 'key' => 'chushu', 'name' => '处暑'],
        ['month' => 9, 'day' => 7, 'key' => 'bailu', 'name' => '白露'],
        ['month' => 9, 'day' => 22, 'key' => 'qiufen', 'name' => '秋分'],
        ['month' => 10, 'day' => 8, 'key' => 'hanlu', 'name' => '寒露'],
        ['month' => 10, 'day' => 23, 'key' => 'shuangjiang', 'name' => '霜降'],
        ['month' => 11, 'day' => 7, 'key' => 'lidong', 'name' => '立冬'],
        ['month' => 11, 'day' => 22, 'key' => 'xiaoxue', 'name' => '小雪'],
        ['month' => 12, 'day' => 6, 'key' => 'daxue', 'name' => '大雪'],
        ['month' => 12, 'day' => 21, 'key' => 'dongzhi', 'name' => '冬至'],
    ],
    '2025' => [
        ['month' => 1, 'day' => 5, 'key' => 'xiaohan', 'name' => '小寒'],
        ['month' => 1, 'day' => 20, 'key' => 'dahan', 'name' => '大寒'],
        ['month' => 2, 'day' => 3, 'key' => 'lichun', 'name' => '立春'],
        ['month' => 2, 'day' => 18, 'key' => 'yushui', 'name' => '雨水'],
        ['month' => 3, 'day' => 5, 'key' => 'jingzhe', 'name' => '惊蛰'],
        ['month' => 3, 'day' => 20, 'key' => 'chunfen', 'name' => '春分'],
        ['month' => 4, 'day' => 4, 'key' => 'qingming', 'name' => '清明'],
        ['month' => 4, 'day' => 20, 'key' => 'guyu', 'name' => '谷雨'],
        ['month' => 5, 'day' => 5, 'key' => 'lixia', 'name' => '立夏'],
        ['month' => 5, 'day' => 21, 'key' => 'xiaoman', 'name' => '小满'],
        ['month' => 6, 'day' => 5, 'key' => 'mangzhong', 'name' => '芒种'],
        ['month' => 6, 'day' => 21, 'key' => 'xiazhi', 'name' => '夏至'],
        ['month' => 7, 'day' => 7, 'key' => 'xiaoshu', 'name' => '小暑'],
        ['month' => 7, 'day' => 22, 'key' => 'dashu', 'name' => '大暑'],
        ['month' => 8, 'day' => 7, 'key' => 'liqiu', 'name' => '立秋'],
        ['month' => 8, 'day' => 23, 'key' => 'chushu', 'name' => '处暑'],
        ['month' => 9, 'day' => 7, 'key' => 'bailu', 'name' => '白露'],
        ['month' => 9, 'day' => 23, 'key' => 'qiufen', 'name' => '秋分'],
        ['month' => 10, 'day' => 8, 'key' => 'hanlu', 'name' => '寒露'],
        ['month' => 10, 'day' => 23, 'key' => 'shuangjiang', 'name' => '霜降'],
        ['month' => 11, 'day' => 7, 'key' => 'lidong', 'name' => '立冬'],
        ['month' => 11, 'day' => 22, 'key' => 'xiaoxue', 'name' => '小雪'],
        ['month' => 12, 'day' => 7, 'key' => 'daxue', 'name' => '大雪'],
        ['month' => 12, 'day' => 21, 'key' => 'dongzhi', 'name' => '冬至'],
    ],
    '2026' => [
        ['month' => 1, 'day' => 5, 'key' => 'xiaohan', 'name' => '小寒'],
        ['month' => 1, 'day' => 20, 'key' => 'dahan', 'name' => '大寒'],
        ['month' => 2, 'day' => 4, 'key' => 'lichun', 'name' => '立春'],
        ['month' => 2, 'day' => 18, 'key' => 'yushui', 'name' => '雨水'],
        ['month' => 3, 'day' => 5, 'key' => 'jingzhe', 'name' => '惊蛰'],
        ['month' => 3, 'day' => 20, 'key' => 'chunfen', 'name' => '春分'],
        ['month' => 4, 'day' => 5, 'key' => 'qingming', 'name' => '清明'],
        ['month' => 4, 'day' => 20, 'key' => 'guyu', 'name' => '谷雨'],
        ['month' => 5, 'day' => 5, 'key' => 'lixia', 'name' => '立夏'],
        ['month' => 5, 'day' => 21, 'key' => 'xiaoman', 'name' => '小满'],
        ['month' => 6, 'day' => 5, 'key' => 'mangzhong', 'name' => '芒种'],
        ['month' => 6, 'day' => 21, 'key' => 'xiazhi', 'name' => '夏至'],
        ['month' => 7, 'day' => 7, 'key' => 'xiaoshu', 'name' => '小暑'],
        ['month' => 7, 'day' => 23, 'key' => 'dashu', 'name' => '大暑'],
        ['month' => 8, 'day' => 7, 'key' => 'liqiu', 'name' => '立秋'],
        ['month' => 8, 'day' => 23, 'key' => 'chushu', 'name' => '处暑'],
        ['month' => 9, 'day' => 7, 'key' => 'bailu', 'name' => '白露'],
        ['month' => 9, 'day' => 23, 'key' => 'qiufen', 'name' => '秋分'],
        ['month' => 10, 'day' => 8, 'key' => 'hanlu', 'name' => '寒露'],
        ['month' => 10, 'day' => 23, 'key' => 'shuangjiang', 'name' => '霜降'],
        ['month' => 11, 'day' => 7, 'key' => 'lidong', 'name' => '立冬'],
        ['month' => 11, 'day' => 22, 'key' => 'xiaoxue', 'name' => '小雪'],
        ['month' => 12, 'day' => 7, 'key' => 'daxue', 'name' => '大雪'],
        ['month' => 12, 'day' => 22, 'key' => 'dongzhi', 'name' => '冬至'],
    ],
];
